version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    allowed_updates: &security_updates
      - match:
          update_type: "security"
    default_reviewers: &default_reviewers
    - asmega
    - sequencemedialimited
    - mattempty
    - form-builder-developers
    - tomas-stefano
    - brenetic
  - package_manager: "docker"
    directory: "/"
    update_schedule: "live"
    allowed_updates: *security_updates
    default_reviewers: *default_reviewers
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers: *default_reviewers
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers: *default_reviewers
